config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :deus do
    resources :likes, only: [:create, :destroy]
  end
  root 'deus#index'
  
  get 'users/like/:id' => 'users#like', as:'user_like'
  


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :deus, dependent: :destroy
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }
  has_many :likes, dependent: :destroy
  has_many :liked_deus, through: :likes, source: :deu
  
  mount_uploader :image, ImageUploader
  def already_liked?(deu)
    self.likes.exists?(deu_id: deu.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
        @deus = User.page(params[:page]).per(3)
    end
    def like
        @user = User.find(params[:id])
        @deus = User.page(params[:page]).per(3)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/like.html.erb
<%= stylesheet_link_tag 'like', :media => "all" %>

<h2>ユーザーがいいねした投稿一覧</h2>
<%= link_to "マイページ", user_path %>

<%= page_entries_info @deus %>
<% @user.liked_deus.each do |t| %>
  <h3>ユーザー名</h3>
  <%= t.user.name %>
  <h3>タイトル</h3>
  <%= t.Title %>
  <h3>本文</h3>
  <%= t.Text%>
  <h3>画像</h3>
  <%= image_tag t.image_url, size: "87x63" if t.image? %>
  
  <span><%= tag.name %></span>
<% end %>

<%= paginate @deus %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users', :media => "all" %>
<h1>ユーザーマイページ</h1>
<p>ユーザーネーム : <%= @user.name %></p>
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>
<%= link_to "記事一覧に戻る", deus_path %>
<%= link_to "いいね一覧", user_like_path %>

<%= page_entries_info @deus %>
<h2>ユーザーの投稿一覧</h2>
<% @user.deus.each do |t| %>
  <h3>タイトル</h3>
  <%= t.Title %>
  <h3>本文</h3>
  <%= t.Text %>
  <h3>参考データ</h3>
  <%= t.Address %>
  <h3>画像</h3>
  <%= image_tag t.image_url, size: "83x67" if t.image? %>
  <%= link_to "編集する", edit_deu_path(t.id) %>
<% end %>

<%= paginate @deus %>

app/views/users/users.html.erb
<h1>ユーザーマイページ</h1>
<p>ユーザーネーム : <%= @user.name %></p>
<p>プロフィール画像 :<%=@deu.image %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registrations_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.deus.each do |t| %>
  <%= t.Title %>
<% end %>

h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_deus.each do |t| %>
  <%= t.user.name %>
  <%= t.Title %>
<% end %>

<%= link_to "記事一覧に戻る", deus_path %>