config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :deus do
    resources :likes, only: [:create, :destroy]
  end
  root 'deus#index'
  
  get 'users/like/:id' => 'users#like', as:'user_like'
  


end

app/models/deu.rb
class Deu < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :deu_tag_relations, dependent: :destroy
    has_many :tags, through: :deu_tag_relations, dependent: :destroy
    
end

app/controllers/deus_controller.rb
class DeusController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
   def index
      @deus= Deu.all
      @tweets = @deus.page(params[:page]).per(3)
      @tags = Tag.all
      @deus = @deus.where( "Title LIKE ? ",'%' + params[:search] + '%') if params[:search].present?
      #もしタグ検索したら、post_idsにタグを持ったidをまとめてそのidで検索
      if params[:tag_ids].present?
        deu_ids = []
        params[:tag_ids].each do |key, value| 
          if value == "1"
            Tag.find_by(name: key).deus.each do |p| 
              deu_ids << p.id
            end
          end
        end
        deu_ids = deu_ids.uniq
        #キーワードとタグのAND検索
        if deu_ids.present?
          @deus = @deus.where(id: deu_ids)
        else
          @deus = @deus.where(id: 0)
        end
      end
    
      
      if params[:tag]
        Tag.create(name: params[:tag])
      end
    end

  def new
     @deu = Deu.new
  end

  def create
    deu = Deu.new(deu_params)
    deu.user_id = current_user.id
    if deu.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @deu = Deu.find(params[:id])
  end
  
  def edit
    @deu = Deu.find(params[:id])
  end

  def update
    deu = Deu.find(params[:id])
    if deu.update(deu_params)
      redirect_to :action => "show", :id => deu.id
    else
      redirect_to :action => "new"
    end
  end
  
  private
  def deu_params
    params.require(:deu).permit(:Title, :Text, :Address, :image, tag_ids: [])
  end
end

app/helpers/deus_helper.rb
module DeusHelper
end

app/views/deus/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>
<%= form_for @deu do |f| %>
  <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
      </div>
    <%= f.label :タイトル %>
    <%= f.text_field :Title, :size => 140 %> 
    <%= f.label :本文 %>
    <%= f.text_area :Text, :size => 140 %> 
    <%= f.label :参考データ %>
    <%= f.text_field :Address, :size => 140 %>
    <%= f.label :image %>
    <%= f.file_field :画像 %>
    <%= f.submit "更新する" %>
    <%= link_to "一覧に戻る", deus_path %>
  <% end %>

app/views/deus/index.html.erb

<%= stylesheet_link_tag 'index', :media => "all" %>

<h3>記事を検索</h3>
<%= form_tag({controller:"deus",action:"index"}, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索する'  %>
  <% end %>
<%= form_tag({controller:"deus",action:"index"}, method: :get) do %>
  <% @tags.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <%= submit_tag '検索' %>
<% end %>


<li class="nav-item active">
<a><%= link_to "新規投稿へ", new_deu_path, class: "nav-link" %></a>
</li>


<li class="nav-item active">
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id), class: "nav-link" %>
<% end %>
</li>

<%= page_entries_info @tweets %>
<h2>記事一覧</h2>
<div class="deus-container">
  <% @deus.each do |t| %>
      <div class="deu">
      
      <div class="main-box">
        <div class="right-container">
         <%= t.Title %>
         <% if user_signed_in? %>
         <%= link_to t.user.name, user_path(t.user.id) %>
         <% end %>
         </div>
        </div>
        <p class="time"><%= t.created_at %></p>
       </div>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to deu_like_path(id: t.id, deu_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
          <% else %>
            <%= button_to deu_likes_path(id: t.id, deu_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
        <% else %>
            <i class="far fa-heart"></i><%= t.likes.count %>
         <% end %>
         
         <%= link_to "詳細へ", deu_path(t.id) %>
         <%= image_tag t.user.image_url, size: "83x67" if t.user.image? %>
         
      </div>
  <% end %>
</div>
<%= paginate @tweets %>







app/views/deus/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<h3>新しい記事</h3>
<%= link_to "一覧に戻る", deus_path %>
<%= form_for @deu do |f| %>
  
    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>
   <div class="post-container">  
     <div class="field">
        <%= f.label :タイトル %>
        <%= f.text_field :Title, :size => 10 %>
     </div>

     <div class="field">
      <%= f.label :本文 %>
      <%= f.text_area :Text, :size => 30*2 %>
     </div>

     <div class="field">
      <%= f.label :参考データ %>
      <%= f.text_field :Address, :size => 10 %>
     </div>

     <div class="field">
      <%= f.label :画像 %>
      <%= f.file_field :image %>
     </div>
  </div>

    <%= f.submit "投稿する" %>
<% end %>

app/views/deus/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<%= link_to "新規投稿へ", new_deu_path %>
<%= link_to "記事一覧に戻る", deus_path %>
<h3>記事詳細</h3>
<div class="deu">
<% @deu.tags.each do |tag| %>
  <span><%= tag.name %></span>
<% end %>
  <h2>タイトル</h2> 
  <p><%= @deu.Title %></p>
  <h2>本文</h2>
  <p><%= @deu.Text %></p>
  <h2>参考データ</h2>
  <p><%= @deu.Address %></p>
  <h2>画像</h2>
  <%= image_tag @deu.image_url, size: "250x200" if @deu.image? %>
  

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@deu) %>
        <%= button_to deu_like_path(@deu), method: :delete do %>
          <i class="fas fa-heart"></i><%= @deu.likes.count %>
        <% end %>
      <% else %>
        <%= button_to deu_likes_path(@deu), method: :post do %>
          <i class="far fa-heart"></i><%= @deu.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= @deu.likes.count %>
    <% end %>
  
</div>

<h2>いいねしたユーザー</h2>
<% @deu.liked_users.each do |user| %>
  <li><%= user.name %></li>
<% end %>
